---
name: site-notifications-config
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'violatordata//$Action/$ID/$Name': Dynamic\Notifications\Controller\ViolatorController

PageController:
  extensions:
    - Dynamic\Notifications\Extension\PageControllerExtension
